# Generated by Django 3.1.1 on 2020-10-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_type', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
