# Generated by Django 3.1.1 on 2020-10-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
