# Generated by Django 3.1.2 on 2020-10-30 18:19

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0004_auto_20201001_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
                ('point_type', models.CharField(max_length=50)),
                ('waste_type', models.IntegerField(choices=[(0, 'Не пластик'), (1, '1-PET-Полиэтилег'), (2, '2-PE-HD-Полиэтилен-высокой-плотности'), (3, '3-PVC-Поливинилхлорид'), (4, '4-PE-LD-Полиэтилен-низкой-плотности'), (5, '5-PP-Полипропилен'), (6, '6-PS-Полистирол'), (7, '7-Другие-пластики')])),
                ('adress', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
