# Generated by Django 3.1.2 on 2020-10-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0005_recyclespot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclespot',
            name='waste_type',
            field=models.IntegerField(),
        ),
    ]
