# Generated by Django 3.1.2 on 2020-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0006_auto_20201030_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclespot',
            name='point_type',
            field=models.IntegerField(),
        ),
    ]
