# Generated by Django 3.1.2 on 2020-11-02 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0008_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 10, 0, 12, 50151)),
            preserve_default=False,
        ),
    ]
