# Generated by Django 3.1.2 on 2020-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booster', '0009_comment_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='recomendations',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
